spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.77.255.131/springboot-security?characterEncoding=utf-8&useSSl=false&serverTimeZone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080